name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ['self-hosted', 'srv085041', 'prod', 'jde']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build
      run: |
        echo "Teste 001"
    - name: Test
      run: |
        echo "Teste 002"
    - name: Deploy
      run: |
        echo "Teste 003"
        python3 main.py
        cat /etc/*-release
        ls -la
        pip3 freeze
        docker ps --all
